# Generated by Django 5.1.5 on 2025-02-04 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_client_nom_alter_client_recette'),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierDeRecouvrement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_a_payer', models.CharField(max_length=20)),
                ('date_paiement', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_rapport', models.CharField(max_length=50)),
                ('date_rapport', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AlterField(
            model_name='client',
            name='adresse',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='nom',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='recette',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients_rec', to='api.recette'),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='recette',
            name='nom_recette',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='dossierderecouvrement',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recouvrement_cli', to='api.client'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiement_cli', to='api.client'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='recette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiement_rec', to='api.recette'),
        ),
    ]
