# Generated by Django 5.1.5 on 2025-02-14 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_dossierderecouvrement_paiement_rapport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recette',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
